cols = {
    "act": "Current Assets Total",
    "aqc": "Acquisitions",
    "capx": "Capital Expenditures",
    "ceq": "Common/Ordinary Equity - Total",
    "ebit": "Earnings Before Interest and Taxes",
    "ebitda": "Earnings Before Interest",
    "epsfi": "Earnings Per Share (Diluted) - Including Extraordinary Items",
    "epsfx": "Earnings Per Share (Diluted) - Excluding Extraordinary Items",
    "epspi": "Earnings Per Share (Basic) - Including Extraordinary Items",
    "epspx": "Earnings Per Share (Basic) - Excluding Extraordinary Items",
    "fincf": "Financing Activities - Net Cash Flow",
    "ivncf": "Investing Activities - Net Cash Flow",
    "oancf": "Operating Activities - Net Cash Flow",
    "revt": "Revenue - Total",
    "seq": "Stockholders Equity - Parent",
    "teq": "Stockholders Equity - Total",
    "xrd": "Research and Development Expense",
    "lct": "Current Liabilities Total",
    "lo": "Liabilities Total Other",
    "lt": "Liabilities Total",
    "ni": "Net Income",
    "at": "Total Assets"
}
